version: 2
models:

- name: dim_customers
  columns:
    - name: c_custkey
      tests:
        - not_null
        - unique

- name: dim_nations
  columns:
    - name: n_nationkey
      tests:
        - not_null
        - unique

- name: dim_parts
  columns:
    - name: p_partkey
      tests:
        - not_null
        - unique

- name: dim_regions
  columns:
    - name: r_regionkey
      tests:
        - not_null
        - unique

- name: dim_suppliers
  columns:
    - name: s_suppkey
      tests:
        - not_null
        - unique

- name: fct_lineitems
  columns:
    - name: l_lineitemkey
      tests:
        - not_null
        - unique

- name: fct_orders
  columns:
    - name: o_orderkey
      tests:
        - not_null
        - unique